services:
  qwen3-devops-server:
    image: vllm/vllm-openai:latest
    container_name: qwen3-devops-server
    runtime: nvidia
    ports:
      - "8001:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./qwen3-devops-final-merged:/app/progtom/devops-model
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model progtom/devops-model
      --host 0.0.0.0
      --port 8000
      --max-model-len 32768
      --gpu-memory-utilization 0.9
      --trust-remote-code
      --enable-auto-tool-choice
      --tool-call-parser hermes
      --enable-reasoning
      --reasoning-parser deepseek_r1
      
    restart: unless-stopped
