services:
  qwen3-training:
    build: .
    container_name: qwen3-devops-training
    runtime: nvidia
    ports:
      - "7860:7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/workspace/.cache/huggingface
      - TRANSFORMERS_CACHE=/workspace/.cache/huggingface
      - HF_DATASETS_CACHE=/workspace/.cache/huggingface/datasets
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: bash